In [2]:
import numpy as np
import pandas as ps

In [7]:
df = ps.read_csv("insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
5      31  female  25.740         0     no  southeast   3756.62160
6      46  female  33.440         1     no  southeast   8240.58960
7      37  female  27.740         3     no  northwest   7281.50560
8      37    male  29.830         2     no  northeast   6406.41070
9      60  female  25.840         0     no  northwest  28923.13692
10     25    male  26.220         0     no  northeast   2721.32080
11     62  female  26.290         0    yes  southeast  27808.72510
12     23    male  34.400         0     no  southwest   1826.84300
13     56  female  39.820         0     no  southeast  11090.71780
14     27    male  42.130         0    yes  southeast  39611.75770
15     19    male  24.600         1     no  southwest   1837.23700
16     52  female  30.780         1     no  northeast  10797.33620
17     23    male  23.845         0     no  northeast   2395.17155
18     56    male  40.300         0     no  southwest  10602.38500
19     30    male  35.300         0    yes  southwest  36837.46700
20     60  female  36.005         0     no  northeast  13228.84695
21     30  female  32.400         1     no  southwest   4149.73600
22     18    male  34.100         0     no  southeast   1137.01100
23     34  female  31.920         1    yes  northeast  37701.87680
24     37    male  28.025         2     no  northwest   6203.90175
25     59  female  27.720         3     no  southeast  14001.13380
26     63  female  23.085         0     no  northeast  14451.83515
27     55  female  32.775         2     no  northwest  12268.63225
28     23    male  17.385         1     no  northwest   2775.19215
29     31    male  36.300         2    yes  southwest  38711.00000
...   ...     ...     ...       ...    ...        ...          ...
1308   25  female  30.200         0    yes  southwest  33900.65300
1309   41    male  32.200         2     no  southwest   6875.96100
1310   42    male  26.315         1     no  northwest   6940.90985
1311   33  female  26.695         0     no  northwest   4571.41305
1312   34    male  42.900         1     no  southwest   4536.25900
1313   19  female  34.700         2    yes  southwest  36397.57600
1314   30  female  23.655         3    yes  northwest  18765.87545
1315   18    male  28.310         1     no  northeast  11272.33139
1316   19  female  20.600         0     no  southwest   1731.67700
1317   18    male  53.130         0     no  southeast   1163.46270
1318   35    male  39.710         4     no  northeast  19496.71917
1319   39  female  26.315         2     no  northwest   7201.70085
1320   31    male  31.065         3     no  northwest   5425.02335
1321   62    male  26.695         0    yes  northeast  28101.33305
1322   62    male  38.830         0     no  southeast  12981.34570
1323   42  female  40.370         2    yes  southeast  43896.37630
1324   31    male  25.935         1     no  northwest   4239.89265
1325   61    male  33.535         0     no  northeast  13143.33665
1326   42  female  32.870         0     no  northeast   7050.02130
1327   51    male  30.030         1     no  southeast   9377.90470
1328   23  female  24.225         2     no  northeast  22395.74424
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [8]:
# Transform string columns into nubmers (categories)
df['sex'] = df['sex'].astype('category')
df['sex'] = df['sex'].cat.codes
df['smoker'] = df['smoker'].astype('category')
df['smoker'] = df['smoker'].cat.codes
df['region'] = df['region'].astype('category')
df['region'] = df['region'].cat.codes
# Print the dataframe
df

      age  sex     bmi  children  smoker  region      charges
0      19    0  27.900         0       1       3  16884.92400
1      18    1  33.770         1       0       2   1725.55230
2      28    1  33.000         3       0       2   4449.46200
3      33    1  22.705         0       0       1  21984.47061
4      32    1  28.880         0       0       1   3866.85520
5      31    0  25.740         0       0       2   3756.62160
6      46    0  33.440         1       0       2   8240.58960
7      37    0  27.740         3       0       1   7281.50560
8      37    1  29.830         2       0       0   6406.41070
9      60    0  25.840         0       0       1  28923.13692
10     25    1  26.220         0       0       0   2721.32080
11     62    0  26.290         0       1       2  27808.72510
12     23    1  34.400         0       0       3   1826.84300
13     56    0  39.820         0       0       2  11090.71780
14     27    1  42.130         0       1       2  39611.75770
15     19    1  24.600         1       0       3   1837.23700
16     52    0  30.780         1       0       0  10797.33620
17     23    1  23.845         0       0       0   2395.17155
18     56    1  40.300         0       0       3  10602.38500
19     30    1  35.300         0       1       3  36837.46700
20     60    0  36.005         0       0       0  13228.84695
21     30    0  32.400         1       0       3   4149.73600
22     18    1  34.100         0       0       2   1137.01100
23     34    0  31.920         1       1       0  37701.87680
24     37    1  28.025         2       0       1   6203.90175
25     59    0  27.720         3       0       2  14001.13380
26     63    0  23.085         0       0       0  14451.83515
27     55    0  32.775         2       0       1  12268.63225
28     23    1  17.385         1       0       1   2775.19215
29     31    1  36.300         2       1       3  38711.00000
...   ...  ...     ...       ...     ...     ...          ...
1308   25    0  30.200         0       1       3  33900.65300
1309   41    1  32.200         2       0       3   6875.96100
1310   42    1  26.315         1       0       1   6940.90985
1311   33    0  26.695         0       0       1   4571.41305
1312   34    1  42.900         1       0       3   4536.25900
1313   19    0  34.700         2       1       3  36397.57600
1314   30    0  23.655         3       1       1  18765.87545
1315   18    1  28.310         1       0       0  11272.33139
1316   19    0  20.600         0       0       3   1731.67700
1317   18    1  53.130         0       0       2   1163.46270
1318   35    1  39.710         4       0       0  19496.71917
1319   39    0  26.315         2       0       1   7201.70085
1320   31    1  31.065         3       0       1   5425.02335
1321   62    1  26.695         0       1       0  28101.33305
1322   62    1  38.830         0       0       2  12981.34570
1323   42    0  40.370         2       1       2  43896.37630
1324   31    1  25.935         1       0       1   4239.89265
1325   61    1  33.535         0       0       0  13143.33665
1326   42    0  32.870         0       0       0   7050.02130
1327   51    1  30.030         1       0       2   9377.90470
1328   23    0  24.225         2       0       0  22395.74424
1329   52    1  38.600         2       0       3  10325.20600
1330   57    0  25.740         2       0       2  12629.16560
1331   23    0  33.400         0       0       3  10795.93733
1332   52    0  44.700         3       0       3  11411.68500
1333   50    1  30.970         3       0       1  10600.54830
1334   18    0  31.920         0       0       0   2205.98080
1335   18    0  36.850         0       0       2   1629.83350
1336   21    0  25.800         0       0       3   2007.94500
1337   61    0  29.070         0       1       1  29141.36030

[1338 rows x 7 columns]

In [10]:
y_train = df['charges'].as_matrix()
y_train = np.reshape(y_train,(len(y_train),1))
y_train

C:\Users\Cordu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

array([[16884.924 ],
       [ 1725.5523],
       [ 4449.462 ],
       ...,
       [ 1629.8335],
       [ 2007.945 ],
       [29141.3603]])

In [11]:
# Drop the output column from the dataframe
df = df.drop(['charges'],axis=1)
df

      age  sex     bmi  children  smoker  region
0      19    0  27.900         0       1       3
1      18    1  33.770         1       0       2
2      28    1  33.000         3       0       2
3      33    1  22.705         0       0       1
4      32    1  28.880         0       0       1
5      31    0  25.740         0       0       2
6      46    0  33.440         1       0       2
7      37    0  27.740         3       0       1
8      37    1  29.830         2       0       0
9      60    0  25.840         0       0       1
10     25    1  26.220         0       0       0
11     62    0  26.290         0       1       2
12     23    1  34.400         0       0       3
13     56    0  39.820         0       0       2
14     27    1  42.130         0       1       2
15     19    1  24.600         1       0       3
16     52    0  30.780         1       0       0
17     23    1  23.845         0       0       0
18     56    1  40.300         0       0       3
19     30    1  35.300         0       1       3
20     60    0  36.005         0       0       0
21     30    0  32.400         1       0       3
22     18    1  34.100         0       0       2
23     34    0  31.920         1       1       0
24     37    1  28.025         2       0       1
25     59    0  27.720         3       0       2
26     63    0  23.085         0       0       0
27     55    0  32.775         2       0       1
28     23    1  17.385         1       0       1
29     31    1  36.300         2       1       3
...   ...  ...     ...       ...     ...     ...
1308   25    0  30.200         0       1       3
1309   41    1  32.200         2       0       3
1310   42    1  26.315         1       0       1
1311   33    0  26.695         0       0       1
1312   34    1  42.900         1       0       3
1313   19    0  34.700         2       1       3
1314   30    0  23.655         3       1       1
1315   18    1  28.310         1       0       0
1316   19    0  20.600         0       0       3
1317   18    1  53.130         0       0       2
1318   35    1  39.710         4       0       0
1319   39    0  26.315         2       0       1
1320   31    1  31.065         3       0       1
1321   62    1  26.695         0       1       0
1322   62    1  38.830         0       0       2
1323   42    0  40.370         2       1       2
1324   31    1  25.935         1       0       1
1325   61    1  33.535         0       0       0
1326   42    0  32.870         0       0       0
1327   51    1  30.030         1       0       2
1328   23    0  24.225         2       0       0
1329   52    1  38.600         2       0       3
1330   57    0  25.740         2       0       2
1331   23    0  33.400         0       0       3
1332   52    0  44.700         3       0       3
1333   50    1  30.970         3       0       1
1334   18    0  31.920         0       0       0
1335   18    0  36.850         0       0       2
1336   21    0  25.800         0       0       3
1337   61    0  29.070         0       1       1

[1338 rows x 6 columns]

In [13]:
x_train = df.as_matrix()
print(x_train)

[[19.    0.   27.9   0.    1.    3.  ]
 [18.    1.   33.77  1.    0.    2.  ]
 [28.    1.   33.    3.    0.    2.  ]
 ...
 [18.    0.   36.85  0.    0.    2.  ]
 [21.    0.   25.8   0.    0.    3.  ]
 [61.    0.   29.07  0.    1.    1.  ]]

C:\Users\Cordu\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

In [14]:
x = x_train / np.linalg.norm(x_train)
y = y_train / np.linalg.norm(y_train)

In [19]:
def train():
    learning_rate = 0.1
    iterations = 10000
    weights = np.random.randn(6,1)
    bias = np.ones((len(x),1))
    for i in range(iterations):
        z = np.dot(x,weights) + bias
        error = 1/(2 * len(x)) * (np.sum((z-y)*(z-y)))
        dcost_dh = 1/len(x) * (z-y)
        dcost_dw = np.dot(x.T, dcost_dh)
        dcost_db = dcost_dh
        if i % 100 ==0:
            print(error)
        weights -= learning_rate * dcost_dw
        bias -= learning_rate * dcost_db
    return weights, bias
w, b = train()

0.49094469274581415
0.47711576852434595
0.46368158474889165
0.450630793222254
0.43795237321946195
0.4256356220193638
0.4136701457102673
0.4020458502616906
0.3907529328545194
0.379781873462084
0.3691234266748931
0.35876861376196806
0.3487087149619237
0.3389352619971472
0.3294400308046109
0.3202150344770477
0.3112525164083982
0.30254494363761325
0.29408500038506946
0.28586558177601984
0.2778797877456641
0.27012091712057995
0.2625824618714085
0.25525810153183576
0.24814169777905423
0.24122728917103095
0.2345090860360393
0.22798146551004872
0.22163896671768973
0.2154762860926376
0.2094882728333783
0.20366992449043797
0.1980163826812683
0.19252292892909337
0.18718498062212802
0.18199808708968399
0.17695792579177932
0.17206029861896485
0.1673011282991779
0.16267645490852398
0.15818243248297825
0.15381532572808565
0.14957150682382225
0.14544745232186343
0.14143974013258329
0.1375450465991897
0.13376014365647063
0.1300818960717037
0.12650725876535035
0.12303327420922545
0.11965706989990021
0.11637585590515957
0.11318692248140101
0.11008763775992098
0.10707544550009435
0.10414786290751263
0.10130247851519877
0.09853695012607491
0.09584900281490923
0.09323642698802083
0.09069707649907119
0.08822886681931916
0.08582977326076324
0.08349782925064086
0.08123112465579782
0.079027804155486
0.07688606566118693
0.07480415878210066
0.07278038333497917
0.07081308789702065
0.06890066840057821
0.06704156676847522
0.06523426958874927
0.06347730682768685
0.0617692505800394
0.06010871385534514
0.058494349399312424
0.056924848549250597
0.05539894012256226
0.0539153893373416
0.052472996764149536
0.051070597308064014
0.0497070592201296
0.04838128313735526
0.04709220115043643
0.04583877589839674
0.04461999968937399
0.04343489364679087
0.04228250688017883
0.04116191567994081
0.04007222273536079
0.03901255637518777
0.03798206983014181
0.03697994051670686
0.03600536934159684
0.03505758002629541
0.03413581845108959
0.033239352018034074
0.03236746903229755
0.031519478101361215

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
reg = LinearRegression().fit(x_train, y_train)
reg.score(x_test,y_test)

0.7602640802497018